```{r}

library(tidyverse)
library(lme4)
library(car)
library(multcomp)
library(readxl)
library(MuMIn)
library(emmeans)
library(here)
```


```{r include=FALSE}
conty_order = c("宜蘭縣","基隆市","臺北市", "新北市",
                "桃園縣","桃園市","新竹市", "新竹縣","苗栗縣",
                "臺中市","彰化縣", "南投縣","南投市",
                "雲林縣","嘉義縣","嘉義市", "臺南市",
                "高雄市", "屏東縣",
                "花蓮縣", "台東縣","臺東縣",
                "Total")
TypeName_order = c("闊葉林",
                   "針葉林",
                   "混淆林",
                   "竹林",
                   "非森林",
                   "Total")

Region2_order = c("North","Center",
                  "South","Southwest",
                  "Hualien","Taitung",
                  "TW")
```

```{r}
library(DBI)
library(RSQLite)

con <-  dbConnect(RSQLite::SQLite(), dbname="D:/R/test/DB/P_BBS.db")
list_Site<- dbReadTable(con, "list_Site") %>% 
  dplyr::select(SiteID, `縣市`, `樣區編號`, `獼猴樣區編號`)
```


```{r}

M.data_F <- 
  list.files(here("./data/clean/Forestry/for analysis/"),
             full.names = T,pattern = "xlsx$|xls$") %>% 
  lapply(., read_excel, sheet="Data", col_types = "text") %>% 
  bind_rows()%>% 
  mutate(Site_N = str_replace_all(Site_N,'MB-C11-10','MA-C11-10')) %>% 
  filter(analysis %in% "Y") %>% 
  filter(Year > 2020) %>% 
  right_join(list_Site, ., by = c("獼猴樣區編號" = "Site_N")) %>% 
  dplyr::select(`SiteID`:`獼猴樣區編號`,Survey, Point,
                Macaca_sur,TypeName.1,Year,Altitude,julian.D) %>% 
  mutate(Data = "Forest")
  
```

```{r}
M.data <- read_excel(here("data/clean/for analysis_1523.xlsx"),
                     sheet=1, col_types = "text") %>% 
  mutate(Macaca_sur = ifelse(is.na(Macaca_sur), 0, Macaca_sur)) %>% 
  filter(analysis %in% "Y") %>% 
  right_join(list_Site, ., by = c("樣區編號" = "Site_N")) %>% 
  dplyr::select(`SiteID`:`獼猴樣區編號`,Survey, Point,
                Macaca_sur,TypeName.1,Year,Altitude,julian.D)%>% 
  mutate(Data = "BBS")
```


```{r}
AllData <- 
bind_rows(M.data, M.data_F) %>% 
  mutate(Region2 = case_when(
    縣市 %in% c("宜蘭縣","基隆市","臺北市","新北市",
                  "桃園市","新竹市","新竹縣","苗栗縣") ~ "North",
    縣市 %in% c("臺中市", "彰化縣","南投縣","南投市")~ "Center",
    縣市 %in% c("雲林縣","嘉義縣","嘉義市", "臺南市")~ "Southwest",
    縣市 %in% c("高雄市", "屏東縣")                  ~ "South",
    縣市 %in% c("花蓮縣")                            ~ "Hualien",
    縣市 %in% c("臺東縣")                            ~ "Taitung"
  )) %>% 
  mutate_at(c("Year", "Survey", "Point", "Macaca_sur","Altitude",
               "julian.D"), as.numeric) %>% 
  mutate(Year.re = Year - min(Year) + 1) 
```

#==============================================

```{r include=FALSE}
df <- 
  AllData 
```


```{r include=FALSE}
df$Altitude.1 <-  scale(df$Altitude,scale =T)
df$julian.D.1 <-  scale(df$julian.D,scale =T)
```



```{r}
m1 <- glm(Macaca_sur ~  TypeName.1 + Year.re + Altitude.1 + julian.D.1 +  Region2 + Data, 
            family = binomial, data = df)
```



```{r}
Anova(m1)

```

```{r}
summary(m1)
```


```{r}
df_fit <- 
fitted(m1) %>% 
  data.frame(fitted = .) %>% 
  bind_cols(df,.)
```


```{r}
ggplot(df_fit, aes(x = as.character(Year), y = fitted))+
  geom_boxplot(aes(col = Data))
  
```

```{r}
df_fit %>% 
  group_by(Year, Data) %>% 
  summarise(value = mean(fitted)) %>% 
  ggplot(., aes(x = Year, y = value)) +
  geom_point(aes(col = Data))+
  geom_line(aes(col = Data))
```

