---
title: "GLMM"
author: '  '
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
library(car)
library(multcomp)
library(readxl)
library(MuMIn)
library(here)

library(flextable)
```

```{r}
M.data <- read_excel(
  here("data/clean/for analysis Forestrydata_2021_V1.xlsx"),
                     sheet="Data")  %>% 
      mutate(Point = as.numeric(Point))%>% 

    bind_rows(
      read_excel(
        here("data/clean/for analysis Forestrydata_V1.xlsx"), sheet="Data") %>% 
      mutate(Macaca_sur = as.numeric(Macaca_sur)) 
             )  %>% 
  
  mutate(Office = ordered(Office,
                          levels = c("羅東", "新竹", "東勢", "南投",
                                     "嘉義", "屏東", "花蓮", "臺東"),
                          labels = c("Luodong", "Hsinchu", "Dougshih", "Nantou",
                                     "Chiayi", "Pingtung", "Hualien", "Taitung"))) %>% 
  
  mutate_at(c("Year", "Survey","Point","Month",
              "Day", "Macaca_sur", "Distance"), as.numeric) %>% 
  
  mutate(TypeName.1 = case_when(
    TypeName.1 %in% "闊葉林" ~ "broad_leaved",
    TypeName.1 %in% "針葉林" ~ "coniferous",
    TypeName.1 %in% "竹林" ~ "Bamboo",
    TypeName.1 %in% "混淆林" ~ "mixed",
    TypeName.1 %in% "非森林" ~ "Not forest"
  )) %>% 

  
  
  filter(analysis %in% "Y")


```

```{r}
M.data <- M.data %>% 
  mutate( Year.re = Year - min(Year) + 1)

```

```{r}

df <- 
  M.data 


```

```{r}
allFit(glmer(Macaca_sur ~ TypeName.1  + Year.re + Altitude + julian.D + Office +  (1|Site_N) + (Year.re|Site_N), 
             family = binomial, data = df))   #嘗試使用一系列優化程序重新擬合glmer模型

```

```{r}
df$Altitude.1 <-  scale(df$Altitude,scale =T)
df$julian.D.1 <-  scale(df$julian.D,scale =T)
```


```{r}
m1 <- glmer(Macaca_sur ~  TypeName.1 + Year.re + Altitude.1 + julian.D.1 + Office  + (1|Site_N)+ (Year.re|Site_N), 
            family = binomial, data = df,
            control = glmerControl(optimizer = "bobyqa"))
```


```{r}
Anova(m1)
```


```{r}
summary(m1)
```


```{r}
qqnorm(resid(m1))
qqline(resid(m1))
```


```{r}
plot(fitted(m1),resid(m1))
```


```{r}
#AICc==============================================

options(na.action = "na.fail")
d1<- dredge(m1,  trace = T)

d1
```


```{r}
summary(model.avg(d1))
```


```{r}
summary(model.avg(d1, subset = delta < 2))
```


```{r}
importance(d1)
```


```{r}
sw(model.avg(d1, subset = delta < 2))
```


```{r}
#-------------------------------------------


summary(glht(m1, linfct = mcp(Office = "Tukey")))
```


```{r}
summary(glht(m1, linfct = c("Year.re = 0",
                            "Altitude.1 = 0",
                            "julian.D.1 = 0")))
```


```{r}
par(mai=c(1,1,1.2,0.2))
glht(m1, linfct = mcp(Office = "Tukey")) %>% cld()  %>% plot
```


```{r}
par(mai=c(1,1.5,1,1))
glht(m1, linfct = mcp(Office = "Tukey")) %>% plot


```

