---
title: "Data Summary of Foresty(內部資料)"
author: '  '
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output: html_document
---

### **2021 林務局獼猴調查情形**

```
1.
2.
3.

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(readxl)
library(writexl)
library(sf)
library(here)

library(flextable)
library(ftExtra)
```


```{r include=FALSE}

M.data <- 
  read_excel(here("data/clean/for analysis Forestrydata_2021_V1.xlsx"),
             sheet="Data")  %>%
#  bind_rows(
#  read_excel("./data/clean/for analysis Forestrydata_V1.xlsx",
#                     sheet="Data"))  %>% 
  mutate(Office = ordered(Office, 
                          c("羅東", "新竹", "東勢", "南投",
                            "嘉義", "屏東", "花蓮", "臺東"))) %>% 
  mutate(TypeName.1 = ordered(TypeName.1,
                              c("闊葉林", "針葉林", "竹林",
                                "混淆林", "非森林"))) %>% 
  mutate_at(c("Year", "Survey","Point","Month",
              "Day", "Macaca_sur", "Distance"), as.numeric) 
  
```


#### 大於兩群的樣點
```{r echo=FALSE, message=FALSE, warning=FALSE}
Group_than2<- M.data %>%
   filter(analysis %in% "Y") %>% 
   filter(!(TypeName.1 %in% "非森林")) %>% 
   filter(Macaca_sur %in% 1) %>% 
   group_by(Year, Survey, Site_N) %>% 
     summarise(N = n()) %>% 
   filter(N>1)

Group_than2 %>% 
  mutate(Year = as.character(Year)) %>% 
  arrange(Site_N) %>% 
  flextable(.) %>% 
   width(., width = c(1,1,2,1)) %>% 
  
  align(.,j = 1:4,
        align = "center", part = "all")  %>% 


  set_header_labels(
    'Site_N' = "樣區編號",
    'N' = "猴群數" ) 

```
\newpage

猴群分布的森林類型
```{r echo=FALSE, message=FALSE, warning=FALSE}
Composition_Forest<- M.data %>% 
   filter(analysis %in% "Y") %>% 
   filter(!(TypeName.1 %in% "非森林")) %>% 
   group_by(TypeName.1,TypeName) %>% 
   summarise(N = n(), m = sum(Macaca_sur))

Composition_Forest %>% 
  flextable(.) %>% 
   width(., width = c(1,2,1,1))  %>%
  
  align(.,
        align = "center", part = "all") %>% 
  set_header_labels(
    'TypeName.1' = "森林類型",
    'TypeName' = "森林類型(森林4th的圖層)",
    'N' = "樣點數",
    'm' = "猴群數" )

```

各林管處的樣點、猴群、相對密度 (mean & se)
```{r echo=FALSE, message=FALSE, warning=FALSE}

E_rate_Office<-
    M.data %>% 
    filter(analysis %in% "Y") %>% 
    filter(!(TypeName.1 %in% "非森林")) %>%
    group_by(Year, Survey, Office) %>%
    summarise(N = n(),
              m = sum(Macaca_sur)) %>% 
    bind_rows(group_by(.,Year, Survey) %>%  #增加total的部分
                summarise(N=sum(N), m = sum(m)) %>%
                mutate(Office='Total')) %>% 
    mutate(E = m/N) %>%
    ungroup() %>%
  
    group_by(Office) %>%
    summarise(Mean_N = mean(N),
              Se_N = sd(N)/sqrt(n()),
              Mean_m = mean(m),
              Se_m = sd(m)/sqrt(n()),
              Mean_E = mean(E),
              Se_E = sd(E)/sqrt(n())) 


E_rate_Office %>%
  mutate(Mean_E = round(Mean_E, 3),
         Se_E = round(Se_E, 3)) %>% 
  mutate(Office = ordered(Office, c('羅東',
                                       '新竹',
                                       '東勢',
                                       '南投',
                                       '嘉義',
                                       '屏東',
                                       '花蓮',
                                       '臺東', 
                                       'Total'))) %>% 
  arrange(Office) %>% 
  flextable(.) %>%
  
  align(.,
        align = "center", part = "all")  
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

tmp.forest <- 
M.data %>%  #非森林的小計
  filter(TypeName.1 %in%　"非森林") %>% 
  group_by(Year, Survey, TypeName.1) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur)) 

tmp.alt <- 
M.data %>%  #<50m & >=50m 分別森林的小計
  filter(!TypeName.1 %in%　"非森林") %>%
  mutate(TypeName.1 = ifelse(Altitude<50, "less50","Forest")) %>%
  group_by(Year, Survey, TypeName.1) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur)) 

E_rate_Forest<-
M.data %>% 
  group_by(analysis, Year, Survey, TypeName.1) %>%
  summarise(N = n(),
            m = sum(Macaca_sur)) %>%  
  bind_rows(group_by(.,Year, Survey) %>% #增加total的部分，total的資料包含非森林及<50m
              summarise(N=sum(N), m = sum(m)) %>%
              mutate(TypeName.1='Total', analysis ="Y")) %>% 
  filter(analysis =="Y") %>%   #移除 非森林及<50m
  select(-analysis)%>% 
  
  bind_rows(., tmp.alt, tmp.forest) %>%  #增加是先算好 森林、非森林、<50的小計
  
  mutate(E = m/N) %>%
  ungroup() %>%
  
  group_by(TypeName.1) %>%
  summarise(Mean_N = mean(N),
            Se_N = sd(N)/sqrt(n()),
            Mean_m = mean(m),
            Se_m = sd(m)/sqrt(n()),
            Mean_E = mean(E),
            Se_E = sd(E)/sqrt(n())) 

E_rate_Forest %>% 
  mutate(TypeName.1 = ordered(TypeName.1, c('Forest',
                                            '闊葉林',
                                       '針葉林',
                                       '竹林',
                                       '混淆林',
                                       '非森林',
                                       'less50',
                                       'Total'))) %>% 
  arrange(TypeName.1) %>% 
  mutate(Mean_E = round(Mean_E,3)) %>% 
  mutate(Se_E = round(Se_E,3)) %>% 
  flextable(.) %>%
  
  align(.,
        align = "center", part = "all") 

```

非森林的樣點離森林的距離
```{r echo=FALSE, message=FALSE, warning=FALSE}

M.data_notForest <- 
M.data %>%  
  filter(TypeName.1 %in% "非森林") %>% 
  mutate(cut = cut(Distance, breaks = seq(20,240,10),
                   include.lowest = T, right = TRUE))

ggplot(M.data_notForest, aes(x = Distance))+
  geom_histogram(fill = gray(0.8), col = "black", breaks = seq(20,240,10))+
  stat_bin( geom="text", colour="black", size=3.5, breaks = seq(20,240,10),
           aes(label=..count.., y=(..count..)+0.6))+
  scale_x_continuous(breaks = seq(20,240,20),expand = c(0,0,0,5))+
  scale_y_continuous(expand = c(0,0,0,5))+
  labs(x = "Distance", y = "Count")+
  theme(
    text = element_text(family="serif"),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5)
  )
 

```

林管處的Encounter_rate
```{r echo=FALSE, message=FALSE, warning=FALSE}
M.data %>% 
  filter(analysis %in% "Y") %>% 
  group_by(Office, Survey, Year) %>% 
  summarise(E = sum(Macaca_sur)/n()) %>% 
  
  ggplot(., aes(x = Office, y = E)) +
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9))+
  scale_y_continuous(breaks = seq(0,0.15,0.05), limits = c(0,0.15))+
  labs(x = "林管處", y = "Encounter_rate")+
  theme(
    text = element_text(family="serif"),
    panel.border = element_rect(size = 1.5,fill = NA),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5)
  )
```

森林類型的Encounter_rate

```{r echo=FALSE, message=FALSE, warning=FALSE}

M.data %>% 
  filter(analysis %in% "Y") %>% 
  group_by(TypeName.1, Survey, Year) %>% 
  summarise(E = sum(Macaca_sur)/n()) %>% 
  
  ggplot(., aes(x = TypeName.1, y = E)) +
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9))+
  scale_y_continuous(breaks = seq(0,0.15,0.05), 
                     limits = c(0,0.15))+
  labs(x = "森林類型", y = "Encounter_rate")+
  theme(
    text = element_text(family="serif"),
    panel.border = element_rect(size = 1.5,fill = NA),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5)
  )

```

Altitude的Encounter_rate
```{r echo=FALSE, message=FALSE, warning=FALSE}
Alt.d.n <-
  M.data %>% 
  filter(analysis %in% "Y") %>% 
  mutate(Altitude_f =cut(Altitude,
                         breaks = c(seq(0,4000,500)),
                         labels = c(seq(250,3750,500)),
                         include.lowest = T) ) %>% 
  group_by(Altitude_f,Survey, Year) %>% 
  summarise(N = n(), E = sum(Macaca_sur)/n()) %>% 
  group_by(Altitude_f) %>% 
  summarise(mean_N = mean(N), 
            E25 = quantile(E,0.25),
            E50 = quantile(E,0.50),
            E75 = quantile(E,0.75)) %>% 
  ungroup()

  M.data %>% 
  filter(analysis %in% "Y") %>% 
  mutate(Altitude_f =cut(Altitude,
                         breaks = c(seq(0,4000,500)),
                         labels = c(seq(250,3750,500)),
                         include.lowest = T) ) %>% 
  group_by(Altitude_f,Survey, Year) %>% 
  summarise(N = n(), E = sum(Macaca_sur)/n()) %>% 
  flextable(.) %>%
  
  align(.,
        align = "center", part = "all")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
M.data %>% 
  filter(analysis %in% "Y") %>% 
  mutate(Altitude_f =cut(Altitude,
                         breaks = c(seq(0,4000,500)),
                         labels = c(seq(250,3750,500)),
                         include.lowest = T) ) %>% 
  group_by(Altitude_f,Survey, Year) %>% 
  summarise(E = sum(Macaca_sur)/n()) %>% 
  ungroup()%>% 
  
  ggplot(., aes(x = Altitude_f, y = E)) +
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9))+
    geom_text(data = Alt.d.n, 
              aes(y = E75,
                label = mean_N),
            size = 4,
            hjust = -0.2, 
            vjust = -0.7,
              position = position_dodge(0.9))+
    
  scale_y_continuous(breaks = seq(0,1,0.2)#,
                 #    limits = c(0,0.10)
                     )+ #0.10
  labs(x = "Elevation (m)",
       y = "Encounter rate (troop/point)") +
  theme(
    text = element_text(family="serif"),
    panel.border = element_rect(size = 1.5,fill = NA),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5)
  )

```

排除3000m以上，再畫一次
```{r echo=FALSE, message=FALSE, warning=FALSE}
M.data %>% 
  filter(analysis %in% "Y") %>%
  mutate(Altitude_f =cut(Altitude,
                         breaks = c(seq(0,4000,500)),
                         labels = c(seq(250,3750,500)),
                         include.lowest = T) ) %>% 
   
  group_by(Altitude_f,Survey, Year) %>% 
  summarise(E = sum(Macaca_sur)/n()) %>% 
  ungroup()%>% 
  
  ggplot(., aes(x = Altitude_f, y = E)) +
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9))+
  geom_text(data = Alt.d.n, 
            aes(y = E75,
                label = mean_N),
            size = 4,
            hjust = -0.2, 
            vjust = -0.7,
            position = position_dodge(0.9))+
  
  scale_y_continuous(breaks = seq(0,0.10,0.02), 
                     limits = c(0,0.10)
                     )+ 
  coord_cartesian(xlim = c(1, 6))+
  labs(x = "Elevation (m)",
      y = "Encounter rate (troop/point)") +
  theme(
    text = element_text(family="serif"),
    panel.border = element_rect(size = 1.5,fill = NA),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5)
  )

```


```{r echo=FALSE, message=FALSE, warning=FALSE}

  M.data %>% 
    filter(analysis %in% "Y") %>% 
    mutate(Altitude_f =cut(Altitude,
                           breaks = c(seq(0,4000,500)),
                           labels = c(seq(250,3750,500)),
                           include.lowest = T) ) %>% 
    group_by(Altitude_f,Survey, Year) %>% 
    summarise(E = sum(Macaca_sur)/n()) %>% 
    group_by(Altitude_f) %>% #確認中位數
    summarise(mid = median(E))

```
猴群分布的海拔 (max Alt = 3075)
```{r echo=FALSE, message=FALSE, warning=FALSE}
M.data %>% 
    filter(analysis %in% "Y") %>% 
  filter(Macaca_sur %in% 1) %>%
  .$Altitude %>% 
  hist(breaks = c(seq(0,3200,100)))

```
樣點的海拔分布
```{r echo=FALSE, message=FALSE, warning=FALSE}
 
  M.data %>% 
    filter(analysis %in% "Y") %>% 
    mutate(Altitude_f =cut(Altitude,
                           breaks = c(seq(0,4000,100)),
                           labels = c(seq(50,4000,100)),
                           include.lowest =T) ) %>% 
    group_by(Altitude_f, Year) %>% 
    summarise(N = n()) %>% 

    ggplot(., aes(x = Altitude_f, y = N))+
    geom_point()
  
  
```

