
```{r include=FALSE}
library(tidyverse)
library(readxl)
library(writexl)
library(here)
library(flextable)
library(ftExtra)

here::here() 

```

```{r}
conty_order = c("宜蘭縣","基隆市","臺北市", "新北市",
                "桃園縣","桃園市","新竹市", "新竹縣","苗栗縣",
                "臺中市","彰化縣", "南投縣","南投市",
                "雲林縣","嘉義縣","嘉義市", "臺南市",
                "高雄市", "屏東縣",
                "花蓮縣", "台東縣","臺東縣",
                "Total")
TypeName_order = c("闊葉林",
                   "針葉林",
                   "混淆林",
                   "竹林",
                   "非森林",
                   "Total")
```

```{r read_data }
M.data <- read_excel(here("./data/clean/for analysis_1521.xlsx"),
                     sheet=1) %>% 
  
  mutate_at(c("Year", "Survey", "Point", "Macaca_sur",
              "Month", "Day", "Distance"), as.numeric) %>% 
  
  mutate(TypeName.1 = ordered(TypeName.1, TypeName_order)) %>% 
  mutate(County = ordered(County,conty_order)) 
  
```


### **原始資料**

#### **調查日3/1~6/30間、包含非森林、包含50m以下**

```{r include=FALSE}
Ori_Macaca <- 
  M.data %>%  
  bind_rows(
     M.data %>%   mutate(County = "Total")
     ) %>%
  mutate(GG = case_when(
    Macaca_sur %in% 1 ~ "G",
    Macaca_sur %in% 0 & !is.na(Macaca_dist) ~ "S",
    TRUE ~ "None"
  )) %>% 
  
  filter(! GG %in% "None") %>% 
  
  split(., .$GG) %>% 
  
  map(., function(x){
    x %>% 
      group_by(Year,  County) %>% 
      summarise(
        '筆數'= Macaca_sur %>% length, 
        '樣區數'= Site_N %>% unique %>% length,
        '樣點數'= paste0(Site_N,"-",Point) %>% unique %>% length
        ) %>% 
      mutate(County = ordered(County, conty_order))%>% 
      reshape2::melt(id = 1:2) %>% 
      reshape2::dcast(variable + Year ~ County) 
    })
```

猴群數量
```{r}
Ori_Macaca$`G` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
  

```

孤猴數量

```{r}
Ori_Macaca$`S` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
```

\newpage

### **分析用** 
#### **調查日3/1~6/30間、"不"包含非森林、"不"包含50m以下**

```{r include=FALSE}
Clean_Macaca <- 
  M.data %>%  
  bind_rows(
     M.data %>%   mutate(County = "Total")
     ) %>%
  mutate(GG = case_when(
    Macaca_sur %in% 1 ~ "G",
    Macaca_sur %in% 0 & !is.na(Macaca_dist) ~ "S",
    TRUE ~ "None"
  )) %>% 
  
  filter(! GG %in% "None") %>% 
  
  filter(analysis %in% "Y") %>% 
  
  split(., .$GG) %>% 
  
  map(., function(x){
    x %>% 
      group_by(Year,  County) %>% 
      summarise(
        '筆數'= Macaca_sur %>% length, 
        '樣區數'= Site_N %>% unique %>% length,
        '樣點數'= paste0(Site_N,"-",Point) %>% unique %>% length
        ) %>% 
      mutate(County = ordered(County, conty_order))%>% 
      reshape2::melt(id = 1:2) %>% 
      reshape2::dcast(variable + Year ~ County) 
    })
```


猴群數量
```{r}
Clean_Macaca$`G` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
  

```

孤猴數量

```{r}
Clean_Macaca$`S` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
```


```{r include=FALSE}
output.1<- 
  M.data %>% 
  mutate(analysis %in% "Y") %>% 
  mutate(TypeName = 
           str_replace_all( TypeName,  "^針闊葉樹混$", "針闊葉樹混淆")) %>%
  mutate(Macaca_sur = ifelse(is.na(Macaca_sur), 0, Macaca_sur) ) %>% 
  group_by(TypeName.1,TypeName) %>% 
  summarise(
    N = n(),
    m = sum(Macaca_sur))
```


\newpage

Region、猴群數、樣區數

```{r warning=FALSE, include=FALSE}
E_rate_Region<- 
  M.data %>%
  bind_rows( M.data %>% mutate(Region2='TW') ) %>%
  
  filter(analysis %in% "Y") %>%
  group_by(Year, Survey, Region2) %>% 
  summarise(
    N= n(),
    m = sum(Macaca_sur,na.rm=T) )  %>% 
  mutate(E = (m/N) %>% round(.,3)) %>%
  ungroup() %>% 
  reshape2::melt(id = 1:3) %>% 
  reshape2::dcast(Region2 + variable ~ Year + Survey,
                  value.var = "value") %>% 
  reshape2::melt(id = 1:2, variable.name = "variable2")  %>% 
  
  bind_rows(     #增加各region2的mean、se部分
    group_by(., Region2, variable) %>% 
      summarise(
        Mean = mean(value),
        Se = sd(value)/sqrt(length(value))
      ) %>% 
  reshape2::melt(id = 1:2, variable.name = "variable2")
  ) %>% 
  mutate(value = ifelse(
    variable == "E",
    sprintf("%06.4f",value),
    ifelse(
      variable2 %in% c("Mean", "Se"),
      sprintf("%0.1f",value),
      value
    )
  )) %>% 
  
  reshape2::dcast(Region2 + variable ~ variable2,
                  value.var = "value") %>% 
  mutate(variable = ordered( variable, c("N", "m", "E"))) %>% 
  mutate(Region2 = ordered(Region2, c("North","Center",
                                      "South","Southwest",
                                      "Hualien","Taitung",
                                      "TW"))) %>% 
  arrange(Region2)
```


```{r echo=FALSE, warning=FALSE}
#畫表

E_rate_Region %>% 
    flextable(., ) %>%
     span_header(.,sep = "[_\\.]")%>%
    merge_v(., j = c("Region2") ) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    align(.,align = "center", part = "all")%>% 
    set_table_properties(layout = "autofit")



```



\newpage

TypeName、猴群數、樣區數
```{r include=FALSE}
E_rate_Forest<-
 M.data %>%  #非森林的小計
  filter(! Month  %in% c(2, 7) & !is.na(X)) %>% 
  filter(TypeName.1 %in% "非森林") %>% 
   
   bind_rows(
     M.data %>%  #<50m & >=50m 分別森林的小計
       filter(! Month  %in% c(2, 7) & !is.na(X)) %>% 
       filter(!TypeName.1 %in%　"非森林") %>%
       mutate(TypeName.1 = ifelse(Altitude<50, "less50","Forest")) 
   )%>% 
  
   bind_rows(
     M.data %>%  #>=50m 
       filter(analysis %in% "Y") 
   ) %>%
  
  
  group_by(Year, Survey, TypeName.1) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm = T)) %>%
  mutate(E = m/N) %>%
  
  reshape2::melt(id = 1:3) %>% 
  group_by(TypeName.1, variable) %>%
  summarise(Mean = mean(value),
            Se = sd(value)/sqrt(length(value))) %>% 
  reshape2::melt(id = 1:2, variable.name = "variable2") %>%
  
  mutate(value = ifelse(
    variable == "E",
    sprintf("%06.4f",value),
    ifelse(
      variable2 %in% c("Mean", "Se"),
      sprintf("%0.1f",value),
      value
    )
  )) %>% 
  
  
  
  reshape2::dcast(TypeName.1 ~ variable + variable2) %>% 
   mutate(TypeName.1 = ordered(TypeName.1, c("Forest",
                                             "闊葉林", "針葉林",
                                             "混淆林", "竹林",
                                             "less50",
                                             "非森林",
                                             "Total"))) %>% 
  arrange(TypeName.1)
```


```{r echo=FALSE}
#畫表
E_rate_Forest %>% 
    flextable(., ) %>%
    span_header(.,sep = "[_]")%>%
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    align(.,align = "center", part = "all")%>% 
    set_table_properties(layout = "autofit")
     

```
年的相對密度
```{r}
E_year <- 
M.data %>% 
  filter(analysis %in% "Y") %>% 
  mutate(Macaca_sur = ifelse(is.na(Macaca_sur), 0, Macaca_sur))%>%
  group_by(Year, Survey) %>% 
  summarise(V1 = sum(Macaca_sur), n = n()) %>% 
  mutate(E = V1/n) %>% 
  group_by(Year) %>%
  summarise(M = sum(V1),
            N = sum(n),
            Encounter_rate = mean(E),
        Se = sd(E)/sqrt(length(E))) 
```

```{r}
ggplot(E_year , aes( Year, Encounter_rate)) +
  geom_point(size = 4)+
  geom_line(size = 1) +
  geom_errorbar(aes(ymin = (Encounter_rate - Se),
                    ymax = (Encounter_rate + Se)),
                width = 0.1,size = 1) +
  #  annotate("text",x=2015.5, y=0.03,label=paste0("mean ± se"),
  #           vjust=0,  color="red", size=8,family="serif")+
  theme_classic() + 
  scale_y_continuous(limits = c(0,0.03),expand = c(0, 0.002, 0, 0))+
  labs(x = "Year", y = "Encounter rate (troop/point)" ) +
  theme(
    text = element_text(family="serif"),
    aspect.ratio = 1,
   # panel.border = element_rect(size = 1.5,fill = NA),
    axis.line = element_line(size = 1, colour = "black"),
    axis.ticks = element_line(size = 1),
    axis.text = element_text(size = 18,colour = "black"),
    axis.title = element_text(size = 20,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )
```

