
```{r include=FALSE}
library(tidyverse)
library(readxl)
library(writexl)
library(here)
library(flextable)
library(ftExtra)
library(showtext)

showtext_auto()
font_add("Microsoft JhengHei", "msjh.ttc")
here::here() 

```

```{r include=FALSE}
conty_order = c("宜蘭縣","基隆市","臺北市", "新北市",
                "桃園縣","桃園市","新竹市", "新竹縣","苗栗縣",
                "臺中市","彰化縣", "南投縣","南投市",
                "雲林縣","嘉義縣","嘉義市", "臺南市",
                "高雄市", "屏東縣",
                "花蓮縣", "台東縣","臺東縣",
                "Total")
TypeName_order = c("闊葉林",
                   "針葉林",
                   "混淆林",
                   "竹林",
                   "非森林",
                   "Total")
```

```{r include=FALSE}
#------------------
site_list <- 
  read_xlsx("//10.40.1.138/Bird Research/BBSTW (20170612)/01_調查/分層隨機取樣的樣區清單 _20221031.xlsx",
            sheet = "樣區表") %>% 
  .[,7] %>% 
  setNames(., "site_list")


```

```{r read_data, include=FALSE}
M.data <- read_excel(here("./研討會_202307/data/clean/for analysis_1521.xlsx"),
                     sheet=1) %>% 
  
  mutate_at(c("Year", "Survey", "Point", "Macaca_sur",
              "Month", "Day",  "Altitude", "julian.D"), as.numeric) %>% 
  
  
  
   filter(Site_N %in% site_list$`site_list`) %>% 
  
  filter(!(Year %in% 2020 & Survey %in% 3))
  
```

### **原始資料**

#### **調查日3/1\~6/30間、包含非森林、包含50m以下**

```{r include=FALSE}
Ori_Macaca <- 
  M.data %>%  
  bind_rows(
     M.data %>%   mutate(County = "Total")
     ) %>%
  mutate(GG = case_when(
    Macaca_sur %in% 1 ~ "G",
    Macaca_sur %in% 0 & !is.na(Macaca_dist) ~ "S",
    TRUE ~ "None"
  )) %>% 
  
  filter(! GG %in% "None") %>% 
  
  split(., .$GG) %>% 
  
  map(., function(x){
    x %>% 
      group_by(Year,  County) %>% 
      summarise(
        '筆數'= Macaca_sur %>% length, 
        '樣區數'= Site_N %>% unique %>% length,
        '樣點數'= paste0(Site_N,"-",Point) %>% unique %>% length
        ) %>% 
      mutate(County = ordered(County, conty_order))%>% 
      reshape2::melt(id = 1:2) %>% 
      reshape2::dcast(variable + Year ~ County) 
    })
```

猴群數量

```{r echo=FALSE}
Ori_Macaca$`G` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
  

```

\newpage

孤猴數量

```{r echo=FALSE}
Ori_Macaca$`S` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
```

\newpage

### **分析用**

#### **調查日3/1\~6/30間、"不"包含非森林、"不"包含50m以下**

```{r include=FALSE}
Clean_Macaca <- 
  M.data %>%  
  bind_rows(
     M.data %>%   mutate(County = "Total")
     ) %>%
  mutate(GG = case_when(
    Macaca_sur %in% 1 ~ "G",
    Macaca_sur %in% 0 & !is.na(Macaca_dist) ~ "S",
    TRUE ~ "None"
  )) %>% 
  
  filter(! GG %in% "None") %>% 
  
  filter(analysis %in% "Y") %>% 
  
  split(., .$GG) %>% 
  
  map(., function(x){
    x %>% 
      group_by(Year,  County) %>% 
      summarise(
        '筆數'= Macaca_sur %>% length, 
        '樣區數'= Site_N %>% unique %>% length,
        '樣點數'= paste0(Site_N,"-",Point) %>% unique %>% length
        ) %>% 
      mutate(County = ordered(County, conty_order))%>% 
      reshape2::melt(id = 1:2) %>% 
      reshape2::dcast(variable + Year ~ County) 
    })
```

猴群數量

```{r echo=FALSE}
Clean_Macaca$`G` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
  

```

\newpage

孤猴數量

```{r echo=FALSE}
Clean_Macaca$`S` %>%
    mutate(Year = as.character(Year)) %>% 
    flextable(., ) %>%
    merge_v(., j = c("variable") ) %>% 
    hline(i = c(7,14)) %>% 
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    set_table_properties(layout = "autofit")
```

```{r include=FALSE}
output.1<- 
  M.data %>% 
  mutate(analysis %in% "Y") %>% 
  mutate(TypeName = 
           str_replace_all( TypeName,  "^針闊葉樹混$", "針闊葉樹混淆")) %>%
  mutate(Macaca_sur = ifelse(is.na(Macaca_sur), 0, Macaca_sur) ) %>% 
  group_by(TypeName.1,TypeName) %>% 
  summarise(
    N = n(),
    m = sum(Macaca_sur))
```

```{r echo=FALSE}
M.data %>% 
   mutate(SP = paste0(Site_N, "_",Point)) %>% 
  group_by(Year) %>% 
  summarise(
    n_Site_N = Site_N %>% unique() %>% length,
    n_Point = SP %>% unique() %>% length
  ) %>% 
  summary()




M.data %>% 
  filter(analysis=="Y") %>% 
   mutate(SP = paste0(Site_N, "_",Point)) %>% 
  group_by(Year) %>% 
  summarise(
    n_Site_N = Site_N %>% unique() %>% length,
    n_Point = SP %>% unique() %>% length
  ) %>% 
  summary()





M.data %>%
  filter(analysis=="Y") %>% 
  summarise(
    length = Site_N %>% unique() %>% length
  ) 


```


\newpage

TypeName、猴群數、樣區數

```{r include=FALSE}
E_rate_Forest<-
 M.data %>%  #非森林的小計
  filter(! Month  %in% c(2, 7) & !is.na(X)) %>% 
  filter(TypeName.1 %in% "非森林") %>% 
   
   bind_rows(
     M.data %>%  #<50m & >=50m 分別森林的小計
       filter(! Month  %in% c(2, 7) & !is.na(X)) %>% 
       filter(!TypeName.1 %in% "非森林") %>%
       mutate(TypeName.1 = ifelse(Altitude<50,
                                  "Forest (EL<50m)",
                                  "Forest (EL>50m)")) 
   )%>% 
  
   bind_rows(
     M.data %>%  #>=50m 
       filter(analysis %in% "Y") 
   ) %>% 
  
   bind_rows(
     M.data %>%  #all 
       filter(! Month  %in% c(2, 7) & !is.na(X)) %>% 
       mutate(TypeName.1 = "Total")
   ) %>%
  
  
  group_by(Year, Survey, TypeName.1) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm = T)) %>%
  mutate(E = m/N) %>%
  
  reshape2::melt(id = 1:3) %>% 
  group_by(TypeName.1, variable) %>%
  summarise(Mean = mean(value),
            Se = sd(value)/sqrt(length(value))) %>% 
  reshape2::melt(id = 1:2, variable.name = "variable2") %>%
  
  mutate(value = ifelse(
    variable == "E",
    sprintf("%06.4f",value),
    ifelse(
      variable2 %in% c("Mean", "Se"),
      sprintf("%0.1f",value),
      value
    )
  )) %>% 
  
  
  
  reshape2::dcast(TypeName.1 ~ variable + variable2) %>% 
   mutate(TypeName.1 = ordered(TypeName.1, c("Forest (EL>50m)",
                                             "闊葉林", "針葉林",
                                             "混淆林", "竹林",
                                             "Forest (EL<50m)",
                                             "非森林",
                                             "Total"))) %>% 
  arrange(TypeName.1)
```

```{r echo=FALSE}
#畫表
E_rate_Forest %>% 
  setNames(., str_replace_all(colnames(.), "^N", "樣點數")) %>%
  setNames(., str_replace_all(colnames(.), "^m", "猴群數")) %>%
  setNames(., str_replace_all(colnames(.), "^E", "相對密度")) %>%
    flextable(., ) %>%
    span_header(.,sep = "[_]")%>%
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    align(.,align = "center", part = "all")%>% 
    set_table_properties(layout = "autofit")
     

```
\newpage

```{r}
E_rate_Rd<-
M.data %>%
  filter(analysis=="Y") %>% 
  group_by(Year, Survey, Rd_factor) %>% 
 summarise(N = n(),
            m = sum(Macaca_sur, na.rm = T)) %>%
  mutate(E = m/N) %>%
  
  reshape2::melt(id = 1:3) %>% 
  group_by(Rd_factor, variable) %>%
  summarise(Mean = mean(value),
            Se = sd(value)/sqrt(length(value))) %>% 
  reshape2::melt(id = 1:2, variable.name = "variable2") %>%
  
  mutate(value = ifelse(
    variable == "E",
    sprintf("%06.4f",value),
    ifelse(
      variable2 %in% c("Mean", "Se"),
      sprintf("%0.1f",value),
      value
    )
  )) %>% 
  
  
  
  reshape2::dcast(Rd_factor ~ variable + variable2) 
```

```{r echo=FALSE}
#畫表
E_rate_Rd %>% 
  setNames(., str_replace_all(colnames(.), "^N", "樣點數")) %>%
  setNames(., str_replace_all(colnames(.), "^m", "猴群數")) %>%
  setNames(., str_replace_all(colnames(.), "^E", "相對密度")) %>%
    flextable(., ) %>%
    span_header(.,sep = "[_]")%>%
    font(part = "all",fontname = "Arial Unicode MS") %>% 
    align(.,align = "center", part = "all")%>% 
    set_table_properties(layout = "autofit")
     

```


\newpage

年的相對密度

```{r E_year, message=FALSE, warning=FALSE, include=FALSE}

E_year <- 
M.data %>% 
  filter(analysis %in% "Y") %>% 
  group_by(Year, Survey) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N)

mean_N <- 
E_year %>% 
  group_by(Year) %>% 
  summarise(mean_N = mean(N),
            position = quantile(Encounter_rate, 0.75))

```

```{r echo=FALSE}
ggplot(E_year, aes(x = Year, y = Encounter_rate, group = Year))+
  geom_boxplot(width = 0.3, fill= gray(.9))+
  geom_text(data = mean_N,
             aes( x = Year, y = position, label = mean_N),
            size = 3, nudge_x = 0.3, nudge_y = 0.001)+
  
  theme_classic() + 
  scale_x_continuous(breaks = 2015:2021, labels = 2015:2021)+
  scale_y_continuous(limits = c(0,0.04),
                     expand = c(0, 0.002, 0, 0))+
  labs(x = "Year", y = "Relative Abundance Index" )+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(linewidth = 1.5,fill = NA),
    axis.line = element_line(linewidth = 1, colour = "black"),
    axis.ticks = element_line(linewidth = 1),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )
```

\newpage

海拔的相對密度

```{r include=FALSE}
Alt.d <- 
  M.data %>% 
  filter(analysis %in% "Y") %>% 
  mutate(Altitude_f = cut(Altitude,
                        breaks = c(seq(0,4000,500)),
                        labels = c(seq(250,3750,500)),
                        include.lowest = T)) %>% 
  group_by(Year, Survey, Altitude_f) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N) 


Alt.d.n <-
  Alt.d %>%
  group_by(Altitude_f) %>% 
  summarise(mean_N = mean(N, na.rm = T)%>% round(.,1),
            y = quantile(Encounter_rate,0.75))

```

```{r Altitude, echo=FALSE}

ggplot(data = Alt.d, aes( x=Altitude_f, y = Encounter_rate)) +
  geom_boxplot(#size = 1,
               width = 0.4, fill= gray(.9),
               outlier.size = 1) +
  
  geom_text(data = Alt.d.n,
            aes( x = Altitude_f, y = y, label = mean_N),
            size = 3,
            nudge_x = 0.3, nudge_y = 0.0018)+

  
  labs(x = "Elevation (m)",
       y = "Relative Abundance Index") +
  theme_classic() +
#  scale_y_continuous(limits = c(0,0.08),
#                     expand = c(0, 0.002, 0, 0))+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(linewidth = 1.5,fill = NA),
    axis.line = element_line(linewidth = 1, colour = "black"),
    axis.ticks = element_line(linewidth = 1),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )


```

\newpage

Latitde的相對密度

```{r warning=FALSE, include=FALSE}
Lat.d <- 
  M.data %>% 
  filter(analysis %in% "Y") %>% 
  mutate(Y_f = cut(Y,
                        breaks = c(seq(21.5,25.5,1)),
                        labels = c(seq(22,25,1)),
                        include.lowest = T)) %>% 
  group_by(Year, Survey, Y_f) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N) 


Lat.d.n <-
  Lat.d %>%
  group_by(Y_f) %>% 
  summarise(mean_N = mean(N, na.rm = T)%>% round(.,1),
            y = quantile(Encounter_rate,0.75))

```

```{r echo=FALSE}

ggplot(data = Lat.d, aes( x=Y_f, y = Encounter_rate)) +
  geom_boxplot(#size = 1,
               width = 0.4, fill= gray(.9),
               outlier.size = 1) +
  
  geom_text(data = Lat.d.n,
            aes( x = Y_f, y = y, label = mean_N),
            size = 3,
            nudge_x = 0.3, nudge_y = 0.0018)+

  
  labs(x = "Latitude (°N)",
       y = "Relative Abundance Index") +
  theme_classic() +
#  scale_y_continuous(
#                     expand = c(0, 0.00, 0, 0))+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(linewidth = 1.0,fill = NA),
    axis.line = element_line(linewidth = 1, colour = "black"),
    axis.ticks = element_line(linewidth = 1),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )


```

\newpage

Julian Day的相對密度

Julian Day = 60，係指第60\~74天，Julian Day = 75，係指第75\~89天，以此類推，僅Julian Day = 180，係指第180\~182天

```{r warning=FALSE, include=FALSE}
Jd.d <- 
  M.data %>% 
  filter(analysis %in% "Y") %>% 

  mutate(julian.D_f = cut(julian.D,
                        breaks = c(seq(60,210,15)),
                        labels = seq(60,195,15),
                        include.lowest = T)) %>% 
  
  group_by(Year, Survey, julian.D_f) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N) 


```

```{r echo=FALSE}
ggplot(Jd.d, aes(julian.D_f, Encounter_rate))+
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9),
               outlier.size = 3) +
  theme_bw() + 
  labs(x = "Julian day",
       y = "Relative Abundance Index")+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(linewidth = 1.5,fill = NA),
    axis.line = element_line(linewidth = 1, colour = "black"),
    axis.ticks = element_line(linewidth = 1),
    axis.text = element_text(size = 11,colour = "black"),
    axis.title = element_text(size = 23,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )
```

\newpage

森林類型的相對密度

```{r message=FALSE, warning=FALSE, include=FALSE}
Type.d <- 
  M.data %>% 
  filter(analysis %in% "Y") %>% 
  mutate(TypeName.1= ordered(TypeName.1,
                             c("闊葉林", "針葉林", "混淆林", "竹林"))) %>% 
   group_by(Year, Survey, TypeName.1) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N)

Type.d.n <-
  Type.d %>%
  group_by(TypeName.1) %>% 
  summarise(mean_N = mean(N, na.rm = T) %>% round(.,1),
            y = quantile(Encounter_rate,0.75))
```

```{r echo=FALSE, warning=FALSE}
ggplot(Type.d, aes(TypeName.1, Encounter_rate))+
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9),
               outlier.size = 3) +
  
    geom_text(data = Type.d.n,
            aes( x = TypeName.1, y = y, label = mean_N),
            size = 3,
            nudge_x = 0.3, nudge_y = 0.0018)+
  
  
  theme_bw() +
  labs(x = "Forest type",
       y = "Relative Abundance Index")+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(linewidth = 1.5,fill = NA),
    axis.line = element_line(linewidth = 1, colour = "black"),
    axis.ticks = element_line(linewidth = 1),
    axis.text = element_text(size = 16,colour = "black"),
    axis.title = element_text(size = 23,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )
```


\newpage

道路類型的相對密度

```{r message=FALSE, warning=FALSE, include=FALSE}
Rd.d <- 
  M.data %>% 
  filter(analysis %in% "Y") %>% 
  group_by(Year, Survey, Rd_factor) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N)

Rd.d.n <-
  Rd.d %>%
  group_by(Rd_factor) %>% 
  summarise(mean_N = mean(N, na.rm = T) %>% round(.,1),
            y = quantile(Encounter_rate,0.75))
```

```{r echo=FALSE, warning=FALSE}
ggplot(Rd.d, aes(Rd_factor , Encounter_rate))+
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9),
               outlier.size = 3) +
  
    geom_text(data = Rd.d.n,
            aes( x = Rd_factor , y = y, label = mean_N),
            size = 3,
            nudge_x = 0.3, nudge_y = 0.0018)+
  
  
  theme_bw() +
  labs(x = "Road type",
       y = "Relative Abundance Index")+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(linewidth = 1.5,fill = NA),
    axis.line = element_line(linewidth = 1, colour = "black"),
    axis.ticks = element_line(linewidth = 1),
    axis.text = element_text(size = 16,colour = "black"),
    axis.title = element_text(size = 23,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )
```

