
```{r include=FALSE}
library(tidyverse)
library(lme4)
library(car)
library(multcomp)
library(readxl)
library(MuMIn)
library(here)
library(flextable)
library(sf)
```


```{r}
ecoregion3 <- 
  st_read(
    "D:/R/test/BBS site name_gis_data/ecoregion3HJShiu2003_97.shp") %>% 
  st_transform( crs=3826) %>% 
  dplyr::select(ZONE41)


```



```{r include=FALSE}

M.data <- read_excel(here("data/clean/for analysis_1521.xlsx"),
                     sheet=1) %>% 
  filter(analysis %in% "Y") %>% 
  mutate(TypeName.1 = case_when(
    str_detect(TypeName ,"混") ~ "mixed",
    str_detect(TypeName ,"竹林") ~  "Bamboo",
    str_detect(TypeName ,"闊葉樹林型") ~  "broad-leaved",
    str_detect(TypeName ,"針葉樹林型") ~  "coniferous",
         TRUE ~ "Not forest"
  )) %>% 
  mutate_at(c("Year", "Survey", "Point", "Macaca_sur",
              "Month", "Day", "Distance", "julian.D"),as.numeric) %>% 
  mutate_at(c("TypeName.1", "Site_N", "Region2"),as.factor)  %>% 
  
  
  st_as_sf(., coords = c("X", "Y"),crs=4326)%>% 
  st_transform( crs=3826) %>% 
  st_join(., ecoregion3) %>% 
  st_drop_geometry()%>% 
  mutate(ZONE41 = as.character(ZONE41)) 
```


#---------------------------------------------------------------------


```{r include=FALSE}
M.data <- M.data %>% 
  mutate(Macaca_sur = ifelse(is.na(Macaca_sur), 0, Macaca_sur)) %>% 
  mutate(Year.re = Year - min(Year) + 1)

```


#==============================================

```{r include=FALSE}
df <- 
  M.data 
```

#-------------------------------------------
```{r eval=FALSE, include=FALSE}
allFit(glmer(Macaca_sur ~ TypeName.1  + Year.re + Altitude + julian.D +  ZONE41 + (1|Site_N), 
             family = binomial, data = df))   #嘗試使用一系列優化程序重新擬合glmer模型


```

```{r include=FALSE}
df$Altitude.1 <-  scale(df$Altitude,scale =T)
df$julian.D.1 <-  scale(df$julian.D,scale =T)
```


```{r}
m1 <- glmer(Macaca_sur ~  TypeName.1 + Year.re + Altitude.1 + julian.D.1 +  ZONE41 + (1|Site_N), 
            family = binomial, data = df,
            control = glmerControl(optimizer = "bobyqa"))
```


```{r}
Anova(m1)

```

```{r}
df %>% 
  filter(Macaca_sur ==1) %>% 
  dim
```


```{r include=FALSE}
summary(m1)


```

```{r include=FALSE}
#AICc==============================================
options(na.action = "na.fail")
d1<- dredge(m1, trace = T)  
#trace = T的話，是把過程都show出來，看有幾種組合。
```


```{r include=FALSE}
d1[d1$delta<2,] 

```


```{r include=FALSE}
summary(model.avg(d1))
summary(model.avg(d1, subset = delta < 2))
```



```{r}
sw(d1)
```


```{r include=FALSE}
sw(model.avg(d1, subset = delta < 2))

```

```{r include=FALSE}

m2 <- glmer(Macaca_sur ~ Altitude.1 + Year.re  +  julian.D.1 +  ZONE41 + (1|Site_N), 
            family = binomial, data = df,
            control = glmerControl(optimizer = "bobyqa"))
```

#anova table

```{r}
Anova(m2)
```


```{r include=FALSE}
summary(m2)
```


```{r}
summary(glht(m2, linfct = mcp(ZONE41 = "Tukey")))
```


```{r}
summary(glht(m2, linfct = c("Year.re = 0",
                            "Altitude.1 = 0",
                            "julian.D.1 = 0")))
```


```{r eval=FALSE, include=FALSE}
par(mai=c(1,1.5,1,1))
glht(m2, linfct = mcp(ZONE41 = "Tukey")) %>% plot


par(mai=c(1,1.5,1,1))
glht(m2, linfct = mcp(ZONE41 = "Tukey")) %>% 
  cld(.,level=0.05) %>% 
plot(.,col="lightgrey")
```

ZONE41的相對密度
```{r include=FALSE}
ZONE41.d <- 
  M.data %>% 
  filter(analysis %in% "Y") %>% 
 
  group_by(Year, Survey, ZONE41) %>% 
  
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N) 


ZONE41d.n <-
  ZONE41.d %>%
  group_by(ZONE41) %>% 
  summarise(mean_N = mean(N, na.rm = T)%>% round(.,1),
            y = quantile(Encounter_rate,0.75))


```


```{r eval=FALSE, include=FALSE}
library(showtext)

showtext_auto()
font_add("Microsoft JhengHei", "msjh.ttc")


ggplot(ZONE41.d, aes( ZONE41, Encounter_rate))+
  geom_boxplot(size = 1, width = 0.4, fill= gray(.9),
               outlier.size = 3)+
  geom_text(data = ZONE41d.n, 
            aes(y = y,
                label = mean_N),
            size = 3,
            hjust = -0.1, 
            vjust = -1,
            position = position_dodge(0.9), show.legend = F)+
  
  theme_bw()+
  scale_x_discrete("分區", labels = c("1" = "北部",
                                        "2" = "東部",
                                        "3" = "西部"),
                   limit=c("1","3","2"))+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(size = 1.5,fill = NA),
    axis.line = element_line(size = 1, colour = "black"),
    axis.ticks = element_line(size = 1),
    axis.text = element_text(size = 18,colour = "black"),
    axis.title = element_text(size = 23,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )

```


```{r E_year, include=FALSE}

E_year <- 
M.data %>% 
  filter(analysis %in% "Y") %>% 
  group_by(Year, Survey) %>% 
  summarise(N = n(),
            m = sum(Macaca_sur, na.rm=T),
            Encounter_rate = m/N)

mean_N <- 
E_year %>% 
  group_by(Year) %>% 
  summarise(mean_N = mean(N),
            position = quantile(Encounter_rate, 0.75))

```

```{r echo=FALSE}
ggplot(E_year, aes(x = Year, y = Encounter_rate, group = Year))+
  geom_boxplot(width = 0.3, fill= gray(.9))+
  geom_text(data = mean_N,
             aes( x = Year, y = position, label = mean_N),
            size = 3, nudge_x = 0.3, nudge_y = 0.001)+
  
  theme_classic() + 
  scale_x_continuous(breaks = 2015:2021, labels = 2015:2021)+
  scale_y_continuous(limits = c(0,0.03),
                     expand = c(0, 0.002, 0, 0))+
  labs(x = "Year", y = "Encounter rate (troop/point)" )+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    aspect.ratio = 1,
    panel.border = element_rect(size = 1.5,fill = NA),
    axis.line = element_line(size = 1, colour = "black"),
    axis.ticks = element_line(size = 1),
    axis.text = element_text(size = 14,colour = "black"),
    axis.title = element_text(size = 18,colour = "black",
                              vjust = -2, hjust = 0.5),
    axis.title.x.bottom = element_text(vjust = -2),
    axis.title.y.left = element_text(vjust = 2),
    axis.ticks.length = unit(.25, "cm"),
    panel.grid = element_blank(),
    plot.margin = margin(30,30,20,20)
  )
```
