
```{r}
#---- load library
library(readxl)
library(writexl)
library(tidyverse)
library(sf)
library(here)
here()
```



```{r}

#欄位名中英文對照

colname_en <- c('Office','Station','Site_N','Name',
                'Year','Month','Day',
                'Survey','Surveyor','Point',
                'TWD97_X','TWD97_Y','Hour','Minute',
                'Macaca_sur','Macaca_dist','Macaca_voice','Habitat', 'Note')

colname_ch <- c('分署','工作站','樣區編號','樣區名稱',
                '年','月','日',
                '旅次','調查者','樣點編號',
                'X座標\\(TWD97\\)','Y座標\\(TWD97\\)','時','分',
                '數量','距離','叫聲','棲地類型\\(主要\\)','備註')
```



```{r}
path <- "./data/clean/Forestry/full_combind/"

DF <- 
list.files(here(path), full.names = T) %>% 
  map(read_excel, sheet = "Data", col_types ="text") %>%
  map(function(x) {
    x %>%
      setNames(str_replace_all(names(.),setNames(colname_en,colname_ch))) %>%
      setNames(str_replace_all(names(x),
                             c("distance" = "Distance",
                               "join_TypeName"= "TypeName"))
             )
    }) %>%
  
  bind_rows()
```


- Macaca_sur = 1 =   猴群
- Macaca_sur = 0 =   非猴群(無、孤猴)
- Macaca_sur = NA =  沒調查

```{r}
write_xlsx(DF, here("data/clean/Forestry/merge/merge_data_2023.xlsx"))


```

