
```{r include=FALSE}
library(tidyverse)
library(lme4)
library(car)
library(multcomp)
library(readxl)
library(MuMIn)
library(here)
library(flextable)
```


```{r include=FALSE}
#------------------
site_list <- 
  read_xlsx("//10.40.1.138/Bird Research/BBSTW (20170612)/01_調查/分層隨機取樣的樣區清單 _20221031.xlsx",
            sheet = "樣區表") %>% 
  .[,7] %>% 
  setNames(., "site_list")


```

```{r include=FALSE}

M.data <- read_excel(here("./研討會_202307/data/clean/for analysis_1521_V2.xlsx"),
                     sheet=1) %>% 
  filter(analysis %in% "Y") %>% 
  mutate(TypeName.1 = case_when(
    str_detect(TypeName ,"混") ~ "mixed",
    str_detect(TypeName ,"竹林") ~  "Bamboo",
    str_detect(TypeName ,"闊葉樹林型") ~  "broad-leaved",
    str_detect(TypeName ,"針葉樹林型") ~  "coniferous",
         TRUE ~ "Not forest"
  )) %>% 
  mutate_at(c("Year", "Survey", "Point", "Macaca_sur",
              "Month", "Day", "Distance", "Altitude", "julian.D"),as.numeric) %>% 
  mutate_at(c("TypeName.1", "Site_N", "Region2"),as.factor)    %>% 
  
   filter(Site_N %in% site_list$`site_list`) %>% 
  
  filter(!(Year %in% 2020 & Survey %in% 3))
  


```
#---------------------------------------------------------------------


```{r include=FALSE}
M.data <- M.data %>% 
  mutate(Macaca_sur = ifelse(is.na(Macaca_sur), 0, Macaca_sur)) 

```


#==============================================

```{r include=FALSE}
df <- 
  M.data %>% 
  setNames(., str_replace_all(colnames(.),
                              c("^X$" = "Longitude",
                                "^Y$" = "Latitude")))
```


```{r include=FALSE}
df$Altitude.1 <-  scale(df$Altitude,scale =T)
df$julian.D.1 <-  scale(df$julian.D,scale =T)
```


```{r}
model <- glmer(Macaca_sur ~  Altitude.1 + julian.D.1 +Latitude+ (1|Site_N) , df, 
             family = binomial(link = "logit") )
car::vif(model)


```

```{r}
library(ggcorrplot)

corr <- 
  df %>% 
  dplyr::select(Altitude,julian.D,Latitude) %>% 
  cor(.) %>% 
  round(1)

ggcorrplot(corr,
           hc.order = TRUE,
           type = "lower",
           lab = TRUE)

```

#-------------------------------------------
```{r eval=FALSE, include=FALSE}
allFit(glmer(Macaca_sur ~ 
               TypeName.1  +  Altitude.1 + julian.D.1 +  Latitude + Rd_factor + Rd_factor+ (1|Site_N),
             family = binomial(link = "logit"), data = df))   #嘗試使用一系列優化程序重新擬合glmer模型


```


```{r}
m1 <- glmer(Macaca_sur ~  TypeName.1 +  Altitude.1 + julian.D.1 +  Latitude + Rd_factor+ (1|Site_N), 
            family = binomial(link = "logit"), data = df,
            control = glmerControl(optimizer = "bobyqa"))
```


```{r}
Anova(m1)

```

```{r}
df %>% 
  filter(Macaca_sur ==1) %>% 
  dim
```


```{r include=FALSE}
summary(m1)


```

```{r include=FALSE}
#AICc==============================================
options(na.action = "na.fail")
d1<- dredge(m1, trace = F)  
#trace = T的話，是把過程都show出來，看有幾種組合。
d1
```


```{r include=FALSE}
d1[d1$delta<2,] 

```


```{r include=FALSE}
summary(model.avg(d1))
summary(model.avg(d1, subset = delta < 2))
```



```{r}
sw(d1)
```


```{r include=FALSE}
sw(model.avg(d1, subset = delta < 2))

```

```{r include=FALSE}

m2 <- glmer(Macaca_sur ~  Altitude.1 + julian.D.1 +  Latitude + (1|Site_N), 
            family = binomial(link = "logit"), data = df,
            control = glmerControl(optimizer = "bobyqa"))
```

#anova table

```{r}
Anova(m2)
```


```{r include=FALSE}
summary(m2)
```


```{r}
summary(glht(m2, linfct = c("Latitude = 0",
                            "Altitude.1 = 0",
                            "julian.D.1 = 0")))
```


```{r eval=FALSE, include=FALSE}
glht(m2, linfct = c("Latitude = 0",
                      "Altitude.1 = 0",
                      "julian.D.1 = 0")) %>%
  confint() %>% 
  broom::tidy(.) %>% 
  arrange(estimate) %>% 
  mutate(lhs = factor(contrast, levels=unique(contrast))) %>%   # unique() returns values in the order they first appear in the data
  ggplot(aes(x=lhs, y=estimate)) +
  geom_hline(yintercept=0, linetype="11", colour="grey60") +
  geom_segment(aes(xend=lhs, y=conf.low, yend=conf.high), size=0.4, 
               arrow=arrow(ends="both", length=unit(0.05, "inches"), angle=70)) + 
  geom_point() +
  coord_flip() +
  labs(x = "", y = "estimate")+
  theme_classic()
```


