
```{r setup, include=FALSE}
#樣點資料檢核
#---- load library

library(tidyverse)
library(readxl)
library(writexl)
library(sf)
library(here)

library(DBI)
library(RSQLite)
```

欄位名中英文對照
```{r}
colname_en <- c('Office','Station','Site_N','Name',
                'Year','Month','Day',
                'Survey','Surveyor','Point',
                'TWD97_X','TWD97_Y','Hour','Minute',
                'Macaca_sur','Macaca_dist','Macaca_voice','Habitat', 'Note')

colname_ch <- c('分署','工作站','樣區編號','樣區名稱',
                '年','月','日',
                '旅次','調查者','樣點編號',
                'X座標\\(TWD97\\)','Y座標\\(TWD97\\)','時','分',
                '數量','距離','叫聲','棲地類型\\(主要\\)','備註')
```



樣點座標

```{r}
con <-  dbConnect(RSQLite::SQLite(), dbname="D:/R/test/DB/P_BBS.db")

list_Point<- dbReadTable(con, "list_Point") %>%
  dplyr::select(`PointID`, 獼猴樣區編號,樣點代號,
         'TWD97_X'=`X_97`, 'TWD97_Y' = `Y_97`, 'tagert_recorded' = recorded) 

list_Site<- dbReadTable(con, "list_Site")

table_Point<- dbReadTable(con, "table_Point") %>% 
  left_join(list_Site, by = "SiteID") %>% 
  dplyr::select(`PointID`, 獼猴樣區編號,樣點代號, recorded) %>% 
  filter(!is.na(獼猴樣區編號))


dbDisconnect(con)  
```


-------------

回收的調查資料
```{r eval=FALSE, include=FALSE}
DF.o<- 
lapply(paste0(here("data/raw/FORESTRYdata/"), "/", 2024:2024), function(x){
  list.files(x, full.names = T, pattern = "_v") %>%  #讀取各2020資料夾內的excel檔名
    lapply(., function(x){
      x %>% 
      excel_sheets(.) %>%   #讀取各excel內的sheet名
      lapply(.,read_excel, path = x,
             col_names = T, col_type = "text", cell_cols("D:T")) %>%  #讀取各sheet的內容
      bind_rows()  
    })
  }) %>%
  bind_rows() %>% 
  setNames(str_replace_all(names(.),setNames(colname_en,colname_ch)))%>% 

  mutate(Site_N = ifelse(Site_N == 'MB-C11-10', 'MA-C11-10', Site_N)) %>% 
  
  left_join(table_Point, by = c('Site_N' = '獼猴樣區編號',
                                'Point' = '樣點代號')) %>% 
  dplyr::select(-Name)%>% 
  mutate(recorded = Sys.Date()%>% as.character, .before = names(.)[1])%>% 
  arrange(str_sub(Site_N, 4,9), Survey, Point) 

```

```{r eval=FALSE, include=FALSE}
con2 <- dbConnect(RSQLite::SQLite(), "data/raw/FORESTRYdata/data.db")


dbWriteTable(con2, 'Data_survey5', DF.o,
             append = T, overwrite = F)

dbDisconnect(con2) 
```


-----
```{r}
con2 <- dbConnect(RSQLite::SQLite(), "data/raw/FORESTRYdata/data.db")


Data_survey <- 
dbReadTable(con2, 'Data_survey5')%>% 
  filter(Year == 2020) 
```


檢核時間
```{r}
time_check <- 
Data_survey %>% 
  mutate(Date = ISOdatetime(Year, Month, Day, Hour, Minute, sec = 0) )%>% 

  #檢核時間
  group_by(Site_N, Survey) %>% 
  arrange(Date, .by_group = T) %>%  #group內排序
  mutate(time_2=  c(Date[2: n()], NA))%>% 
  mutate(time_diff = difftime(time_2, Date, units='mins') %>% 
           as.numeric())  %>% 
  select(-time_2) %>% 
  
  mutate(day_diff = difftime(Date[n()], Date[1], units='days') %>% 
           as.numeric() %>% round(.,0)) %>%
  
  ungroup() %>% 
  select(DataID,Date,  time_diff, day_diff)
```

```{r}
locate_check <-
Data_survey %>% 
  filter(!is.na(Macaca_sur)) %>% 
  select(DataID,TWD97_X,TWD97_Y,PointID)%>% 

  #檢核位置
  left_join(list_Point,
            by = c("PointID" ),
            suffix = c(".ori", "")) %>% 
  
  #為了計算距離，先轉成"數字格式"
  mutate_at(c("TWD97_X", "TWD97_Y", "TWD97_X.ori", "TWD97_Y.ori"), as.numeric) %>% 
  

  #計算距離
  mutate(point_diff = ifelse(
    is.na(TWD97_X)| is.na(TWD97_Y), NA,
    st_distance(
      st_as_sf(., coords = c("TWD97_X.ori", "TWD97_Y.ori"),
               crs = 3826, remove = F, na.fail = F),#調查位置
      
      st_as_sf(., coords = c("TWD97_X", "TWD97_Y"),
               crs = 3826, remove = F, na.fail = F),#表定位置
      by_element = TRUE) %>% 
      as.numeric()
    )) %>% 
  select(DataID,  point_diff, tagert_recorded)
```

```{r}
check_table <- 
  time_check %>% 
  full_join(locate_check, by = 'DataID') %>% 
  mutate(analysis = "Y", .after = "DataID") %>% 
  mutate(check_data = Sys.Date()%>% as.character,
         .after = 'tagert_recorded')%>% 
  
  
  
  #判斷是否符合標準
  mutate(analysis = ifelse(time_diff<6 & !is.na(time_diff),
                           paste0(analysis, ", 6min"), analysis)) %>% 
  mutate(analysis = ifelse(day_diff > 7 & !is.na(day_diff), 
                           paste0(analysis, ", 7day"), analysis)) %>% 
  
  mutate(analysis = ifelse(data.table::as.ITime(Date) > data.table::as.ITime("10:54"), 
                           paste0(analysis, ", Toolate"), analysis))%>% 
  
  mutate(analysis = case_when(
             point_diff > 51 | is.na(point_diff) ~ paste0(analysis, ", locate"),  # range of gps =50m
             # Point %in% "X" ~ paste0(analysis, ", locate"),  # range of gps =50m
             # str_detect(Note, "刪除") ~ paste0(analysis, ", locate"),
             TRUE ~ analysis)) %>% 
  mutate(analysis = str_replace(analysis, "Y, ","")) %>% 
  select(-Date)
  

```

