---
title: '20250901-猴群數估算'
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(writexl)
library(sf)
library(here)

library(data.table)

```


# **林業署**

```{r include=FALSE}

M.data_F <- 
  here("./data/clean/Forestry/for analysis/") %>% 
  list.files(., full.names = T) %>% 
  str_subset(paste0(2020:2024)) %>% #如果只要2020~2022年，就寫2020:2022
  lapply(., read_excel, sheet="Data", col_types = "text") %>% 
  bind_rows() %>% 

  mutate_at(c("Year", "Survey","Month",
              "Day", "Macaca_sur", "Distance", "Altitude", "julian.D"), as.numeric) %>% 
  filter(analysis %in% "Y") %>% 
  filter(Year > 2020) %>% 
  mutate_at(c("Year"), as.integer)
```

相對密度(群/樣點)圖

```{r include=FALSE}

E_year_F <-
M.data_F %>% 
  setDT %>% 
  .[, .(N = length(Macaca_sur),
        m = sum(Macaca_sur, na.rm=T)
        ),
   by =  c('Year', 'Survey')] %>% 
  .[,Encounter_rate := m/N] %>% 
  
  .[, .(log_E = log(mean(Encounter_rate ))),
  by =  c('Year')] 

```

```{r include=FALSE}
lm(log_E ~ Year, E_year_F) %>% 
  summary
```


```{r eval=FALSE, include=FALSE}

ggplot(E_year_F, aes(x = Year, y = log_E))+
  geom_point()+
  geom_smooth(method = lm,formula = y ~ x, se = F)+
  annotate("text",x = 2023.5, y = -3.15,
    label = "y = -0.08x + 159.37086 \n (p > 0.05)")+
  
  scale_x_continuous(breaks = 2015:2024)+
  labs(y = "Log (相對密度)")+
  theme_classic()

```

\newpage

估計**林班地**猴群數

```{r include=FALSE}
df_F <- 
  M.data_F %>% 
  .[is.na(Macaca_sur), Macaca_sur := 0] %>% 
  .[, Year := as.numeric(Year)] %>% 
  .[, Office := ifelse(Office == "東勢", "臺中", Office)] %>% 
  .[, Office := ifelse(Office == "羅東", "宜蘭", Office)] %>% 
  setDT %>% 
  .[!(TypeName.1 %in% "非森林"), ]

#bootstrap-------------------------
bb_F<- df_F %>% setDT %>% 
  .[, A := ifelse(Macaca_dist %in% "A", Macaca_sur,0)] %>% 
  .[, AB := ifelse(Macaca_dist %in% c("A","B"), Macaca_sur,0)]

#A僅使用25m內的猴群
#AB使用100m內的猴群

```

```{r include=FALSE}

#重複抽樣10000次----
bootstrap_AB_F <- 
bb_F %>% 
  split(., .$Year) %>% 
  lapply(., function(x){
    replicate(10000, mean(sample(x$AB, replace = TRUE), na.rm = T)) 
  })%>% 
  lapply(., function(x){
    data.frame(
    'q_1' = quantile(x, probs = 0.025),
     'mm' = mean(x),
    'q_3' = quantile(x, probs = 0.975)
    )
  }) %>% 
  bind_rows(.id = 'Year') %>% 
  mutate('Year'  = as.integer(Year))


  row.names(bootstrap_AB_F) <- NULL
      


```


國有林班地內海拔50m以上的森林總面積=13812.00 (km^2^)\
方法：bootstrap\
重複抽樣：10,000次\
單位面積的半徑: 100m

```{r include=FALSE}
per_Area <- (0.1*0.1*pi)   #100m半徑的單位原面積

troop_M_F <- 
 bootstrap_AB_F %>%
   setDT %>% 
   .[ , 'M_troops' := (13812.00/per_Area)*mm] %>% 
  .[ , 'q1_troops' := (13812.00/per_Area)*q_1] %>% 
  .[ , 'q3_troops' := (13812.00/per_Area)*q_3] %>% 
  .[, 'log_troops':= log(M_troops)]%>% 
  .[ , 'COUNT' := M_troops*25] 


```


```{r echo=TRUE}
  troop_M_F %>% 
  arrange(M_troops) %>% 
  select(-log_troops) %>% 
  
  flextable::flextable()
```


```{r echo=FALSE}

ggplot(troop_M_F, aes(x = Year, y = M_troops))+
  geom_point()+
  geom_errorbar(aes(ymin = q1_troops,
                    ymax = q3_troops),width=0.1)+
  geom_text(data = troop_M_F, 
            aes(y = M_troops,
                label = as.integer(M_troops)),
            size = 4.5,
            hjust = -0.1, 
            vjust = -1,
            position = position_dodge(0.9), show.legend = F)+
  
  scale_y_continuous(breaks = seq(0,25000,5000), limits = c(0,25000))+

  labs(x = "",y = "猴群數(95%CI)")+

  theme_classic()+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    panel.border = element_rect(linewidth = 1.5,fill = NA),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = 20,colour = "black"),
    axis.title = element_text(size = 18,colour = "black"),
    axis.title.y = element_text(angle = 270,
                              vjust = 0, hjust = 0.5),
    legend.position = "top"
  )

ggsave(here("./林務局年報2024/猴YERA2.PNG"),
       dpi = 300,
       width = 895,
       height = 879,
       units = "px")
```




\newpage

估計**分署**猴群數 
50m以上的森林，2021-2024的資料bootstraps


```{r}

forest_office<- read_xlsx(
  here::here("./林務局年報2024/分署轄內50m以上的森林面積.xlsx")) %>% 
  select(-perimeter) %>% 
  mutate(area = area/1000000)  #換成km2

```




```{r include=FALSE}

#重複抽樣10000次----
bootstrap_AB_Office_F <- 
bb_F %>% 
  split(., .$Office) %>% 
  lapply(., function(x){
    replicate(10000, mean(sample(x$AB, replace = TRUE), na.rm = T)) 
  })%>% 
  lapply(., function(x){
    data.frame(
    'q_1' = quantile(x, probs = 0.025),
     'mm' = mean(x),
    'q_3' = quantile(x, probs = 0.975)
    )
  }) %>% 
  bind_rows(.id = 'Office') 


  row.names(bootstrap_AB_Office_F) <- NULL
      

  
  
  
  troop_Office_F <- 
    bootstrap_AB_Office_F %>% 
    left_join(forest_office,., by = 'Office') %>% 
   setDT %>% 
   .[ , 'M_troops' := (area/per_Area)*mm] %>% 
  .[ , 'q1_troops' := (area/per_Area)*q_1] %>% 
  .[ , 'q3_troops' := (area/per_Area)*q_3] %>% 
  .[, 'log_troops':= log(M_troops)]%>% 
  .[ , 'COUNT' := M_troops*25] 

```

```{r echo=TRUE}
  troop_Office_F %>% 
  arrange(M_troops) %>% 
  select(-log_troops) %>% 
  
  flextable::flextable()
```

```{r echo=FALSE}

ggplot(troop_Office_F, aes(x = Office, y = M_troops))+
  geom_point()+
  geom_errorbar(aes(ymin = q1_troops,
                    ymax = q3_troops),width=0.1)+
  
    geom_text(data = troop_Office_F, 
            aes(y = M_troops,
                label = as.integer(M_troops)),
            size = 4.5,
            hjust = -0.25, 
            vjust = -1,
            position = position_dodge(0.9), show.legend = F)+
   scale_y_continuous(breaks = seq(0,6000,1500), limits = c(0,6500))+

    scale_x_discrete(limits = c( "新竹", "臺中", "宜蘭", "南投",
                                "嘉義", "屏東", "花蓮", "臺東")
  )+
  labs(x = "",y = "猴群數(95%CI)")+

  theme_classic()+
  theme(
    text = element_text(family="Microsoft JhengHei"),
    panel.border = element_rect(linewidth = 1.5,fill = NA),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = 20,colour = "black"),
    axis.title = element_text(size = 18,colour = "black"),
    axis.title.y = element_text(angle = 270,
                              vjust = 0, hjust = 0.5),
    legend.position = "top"
  )


ggsave(here("./林務局年報2024/猴群Office2.PNG"),
       dpi = 300,
       width = 895,
       height = 879,
       units = "px")

```

```{r}

write_xlsx(
  list(
   '猴群YEAR'= troop_M_F,
   '猴群Office'=troop_Office_F 
  ),
  here("./林務局年報2024/bootstrat.xlsx")
)

```

