---
title: "trim_猴群估算"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(writexl)
library(here)

library(data.table)
library(rtrim)
library(flextable)
library(RColorBrewer) 
```


```{r}
M.data <- read_excel(here("./data/clean/for analysis_1523.xlsx"),
                     sheet=1) %>% setDT %>% 
  
  .[analysis %in% "Y",]%>% 

  .[, Year := as.numeric(Year)] %>% 
  .[, Survey := as.numeric(Survey)] %>% 
  .[, Point := as.numeric(Point)] %>% 
  .[, Macaca_sur := as.numeric(Macaca_sur)] %>% 
  .[, Month := as.numeric(Month)] %>% 
  .[, Day := as.numeric(Day)] %>% 
  .[, Distance := as.numeric(Distance)] %>% 
  .[, julian.D := as.numeric(julian.D)] %>% 
  .[, TypeName.1 := as.factor(TypeName.1)] %>% 
  .[, Site_N := as.factor(Site_N)] %>% 
  .[, Region2 := as.factor(Region2)] 
```


```{r}
#----------------------------

county.area <- 
  read.csv(here("./data/clean/gis/county area-3.csv"), header = T) %>%  #因為編碼問題所以從county area-2換成county area-3
  setDT %>% 
  setnames(.,c("County", "Area", "perimeter")) %>% 
  .[County %in% list("宜蘭縣","基隆市","台北市","臺北市",
                     "新北市","台北縣","臺北縣",
                     "桃園縣","桃園市","新竹市",
                     "新竹縣","苗栗縣"), Region := "North"] %>%
  .[County %in% list("台中市","臺中市",
                     "台中縣","臺中縣",
                     "彰化縣","南投縣","南投市",
                     "雲林縣","嘉義縣","嘉義市"), Region := "Center"] %>%
  .[County %in% list("台南市","臺南市",
                     "台南縣","臺南縣",
                     "高雄縣","高雄市",
                     "屏東縣"), Region := "South"]%>%
  .[County %in% list("花蓮縣",
                     "台東縣","臺東縣"), Region := "East"] %>% 
  
  
  
  .[County %in% list("宜蘭縣","基隆市","台北市","臺北市",
                     "新北市","台北縣","臺北縣",
                     "桃園縣","桃園市","新竹市",
                     "新竹縣","苗栗縣"), Region2 := "North"] %>% 
  .[County %in% list("台中市","臺中市",
                     "台中縣","臺中縣",
                     "彰化縣","南投縣","南投市"), Region2 := "Center"] %>% 
  .[County %in% list("雲林縣","嘉義縣","嘉義市",
                     "台南市","臺南市",
                     "台南縣","臺南縣"), Region2 := "Southwest"] %>%
  .[County %in% list("高雄縣","高雄市",
                     "屏東縣"), Region2 := "South"]%>%
  .[County %in% list("花蓮縣"), Region2 := "Hualien"] %>%
  .[County %in% list("台東縣","臺東縣"), Region2 := "Taitung"] %>% 
  
  .[!is.na(Region2),] %>% 
  .[, .(area=sum(Area)), by = list(Region2)] %>% 
  .[, prob_Area:= (area/sum(area))] %>% 
  .[, Region2 := as.character(Region2)]

weight <- 
  M.data %>% 
  setDT  %>% 
  .[, Region2 := as.character(Region2)]%>% 
  .[is.na(Macaca_sur), Macaca_sur := 0] %>% 
  #.[Year < 2019,] %>%
  .[!(TypeName.1 %in% "Not forest"), ] %>% 
  .[, SP := paste0(Site_N,"-",Point)]  %>%
  .[, list(Year, SP, Survey, Region2)] %>%
  .[, .(point_n = .N), by = list(Year, SP, Region2)] %>% 
  .[, SP_n := .N, by = list(Year,Region2)] %>%
  left_join(county.area)  %>% setDT %>%
  .[, weight := (prob_Area / SP_n /point_n)]  



df <- 
  M.data %>% 
  setDT %>% 
  .[is.na(Macaca_sur), Macaca_sur := 0] %>% 
#  .[Year >2020 & Year < 2024,] %>%
  .[!(TypeName.1 %in% "Not forest"), ] %>% 
  .[, SP := paste0(Site_N,"-",Point)] %>% 
  .[, .(number = sum(Macaca_sur)), by = list(Year, SP, Region2, Altitude)] %>% 
  .[, N := sum(number), by = list(SP, Region2)] %>% 
  left_join(weight[, c(1:2, 8)])  %>% setDT %>%
  .[!(N %in% 0),] %>% 
  .[, N := NULL] %>% 
  .[, Region2 := factor(Region2)] %>% 
  .[,Altitude := NULL] %>% 
  setDF 
```



```{r include=FALSE}
m1 <- trim(
  number ~ SP + Year + Region2 ,
  weights = "weight",df,
  model =  2,
  changepoints = "all",
  overdisp = F,
  serialcor = F, 
  autodelete = T, 
  stepwise = F)
```


```{r}
overall(m1, "imputed") %>% plot
```


```{r}
#校正後 (有內插)

m1$tt_imp #校正後相對密度
```


```{r}
#校正後 (有內插)
m1$var_tt_imp %>% diag %>% sqrt#se
```

```{r}
#校正後的count

adj_count <- 
  m1$imputed*m1$wt %>%  
  as.data.frame() %>% 
  setNames(.,c(m1$time.id)) 

bbbb <- 
adj_count %>% 
  
lapply(., function(x){
  replicate(10000, sum(sample(x, replace = TRUE), na.rm = T))
  
  })%>% 
  lapply(., function(y){
    list(
    'q_1' = quantile(y, probs = 0.025),
     'mm' = mean(y),
    'q_3' = quantile(y, probs = 0.975)
    )
  })  %>% 
  bind_rows(.id = 'Year') 


  
plot(mm ~Year,bbbb, type = "o")

```


```{r}


mapply( function(x, y){
 d_sampling <-  sample(1:length(x), replace = TRUE)
 #   mu = m1$imputed[d_sampling]
 # wt = m1$wt[d_sampling]
 # muwt  =  m1$imputed[d_sampling]*m1$wt[d_sampling]
 # summuwt = sum(m1$imputed[d_sampling]*m1$wt[d_sampling])
 # sumwt = sum(m1$wt[d_sampling])
 # 
 # list(
 #   mu = mu,
 # wt = wt,
 # muwt  =  muwt,
 # summuwt = summuwt,
 # sumwt = sumwt,
 # H = summuwt/sumwt
 # 
 # )
 sum(m1$imputed[d_sampling]*m1$wt[d_sampling])/sum(m1$wt[d_sampling])
 
},
split(m1$imputed, col(m1$imputed)),
split(m1$wt, col(m1$wt)), SIMPLIFY = F)



```



# 林業署

```{r}
library(DBI)
```

```{r}
con <-  dbConnect(RSQLite::SQLite(), dbname="D:/R/test/DB/P_BBS.db")

list_Site<- dbReadTable(con, "list_Site") %>% 
  select(獼猴樣區編號, County = 縣市)


dbDisconnect(con)  

```



```{r}
M.data_F <- 
  here("./data/clean/Forestry/for analysis/") %>% 
  list.files(., full.names = T) %>% 
  str_subset(paste0(2020:2024)) %>% #如果只要2020~2022年，就寫2020:2022
  lapply(., read_excel, sheet="Data", col_types = "text") %>% 
  bind_rows() %>% 

  mutate_at(c("Year", "Survey","Month",
              "Day", "Macaca_sur", "Distance", "Altitude", "julian.D"), as.numeric) %>% 
  filter(analysis %in% "Y") %>% 
  filter(Year > 2020) %>% 
  mutate_at(c("Year"), as.integer) %>% 
  left_join(list_Site, by = c("Site_N" = "獼猴樣區編號")) %>% 
  mutate(Region2 = case_when(
    County %in% list("宜蘭縣","基隆市","台北市","臺北市",
                     "新北市","台北縣","臺北縣",
                     "桃園縣","桃園市","新竹市",
                     "新竹縣","苗栗縣") ~ "North",
    County %in% list("台中市","臺中市",
                     "台中縣","臺中縣",
                     "彰化縣","南投縣","南投市") ~ "Center",
    County %in% list("雲林縣","嘉義縣","嘉義市",
                     "台南市","臺南市",
                     "台南縣","臺南縣") ~ "Southwest",
    County %in% list("高雄縣","高雄市",
                     "屏東縣") ~ "South",
    County %in% list("花蓮縣") ~ "Hualien",
    County %in% list("台東縣","臺東縣") ~ "Taitung"
    
  ))%>% 
  filter(Year >= 2021 & Year <= 2023)


```

```{r}


weight_F <- 
  M.data_F %>% 
  setDT  %>% 
  .[, Region2 := as.character(Region2)]%>% 
  .[is.na(Macaca_sur), Macaca_sur := 0] %>% 
  #.[Year < 2019,] %>%
  .[!(TypeName.1 %in% "Not forest"), ] %>% 
  .[, SP := paste0(Site_N,"-",Point)]  %>%
  .[, list(Year, SP, Survey, Region2)] %>%
  .[, .(point_n = .N), by = list(Year, SP, Region2)] %>% 
  .[, SP_n := .N, by = list(Year,Region2)] %>%
  left_join(county.area)  %>% setDT %>%
  .[, weight := (prob_Area / SP_n /point_n)]  



df_F <- 
  M.data_F %>% 
  setDT %>% 
  .[is.na(Macaca_sur), Macaca_sur := 0] %>% 
#  .[Year >2020 & Year < 2024,] %>%
  .[!(TypeName.1 %in% "Not forest"), ] %>% 
  .[, SP := paste0(Site_N,"-",Point)] %>% 
  .[, .(number = sum(Macaca_sur)), by = list(Year, SP, Region2, Altitude)] %>% 
  .[, N := sum(number), by = list(SP, Region2)] %>% 
  left_join(weight_F[, c(1:2, 8)])  %>% setDT %>%
  .[!(N %in% 0),] %>% 
  .[, N := NULL] %>% 
  .[, Region2 := factor(Region2)] %>% 
  .[,Altitude := NULL] %>% 
  setDF 
```

```{r}
m1_F <- trim(
  number ~ SP + Year + Region2 ,
  weights = "weight",df_F,
  model =  2,
  changepoints = "all",
  overdisp = F,
  serialcor = F, 
  autodelete = T, 
  stepwise = F)
```



```{r}
overall(m1_F, "imputed") %>% plot
```


```{r}
#校正後 (有內插)

m1_F$tt_imp #校正後相對密度
```


```{r}
#校正後 (有內插)
m1_F$var_tt_imp %>% diag %>% sqrt#se
```

```{r}
#校正後的count
adj_count_F <- 
  m1_F$imputed*m1_F$wt %>%  
  as.data.frame() %>% 
  setNames(.,c(m1_F$time.id)) 

bbbb_F <- 
adj_count_F %>% 
  
lapply(., function(x){
  replicate(10000, sum(sample(x, replace = TRUE), na.rm = T))
  
  })%>% 
  lapply(., function(y){
    list(
    'q_1' = quantile(y, probs = 0.025),
     'mm' = mean(y),
    'q_3' = quantile(y, probs = 0.975)
    )
  })  %>% 
  bind_rows(.id = 'Year') 

 plot(mm ~Year,bbbb_F, type = "o")
```


```{r}
 
  

ggplot(bbbb, aes(x= as.numeric(Year), y = mm))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin = q_1,
                    ymax = q_3),width=0.1)+
  geom_point(data = bbbb_F, aes(x= as.numeric(Year), y = mm), col="red")+
  geom_line(data = bbbb_F, aes(x= as.numeric(Year), y = mm), col="red")+
  geom_errorbar(data = bbbb_F,aes(ymin = q_1,
                    ymax = q_3),width=0.1, col="red")+
  theme_classic()
  


```

